// <auto-generated />
using System;
using Asp.netWebDatVe.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Asp.netWebDatVe.Migrations
{
    [DbContext(typeof(QLDatVeContext))]
    partial class QLDatVeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Asp.netWebDatVe.Models.BenXe", b =>
                {
                    b.Property<int>("MaBenXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBenXe"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenBenXe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThanhPho")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaBenXe")
                        .HasName("PK__BenXe__436ED7BA873F7318");

                    b.ToTable("BenXe", (string)null);
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.ChuyenXe", b =>
                {
                    b.Property<int>("MaChuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuyen"), 1L, 1);

                    b.Property<string>("BienSoXe")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GiaVe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<int?>("MaNhanVien1")
                        .HasColumnType("int");

                    b.Property<int?>("MaTaiXe")
                        .HasColumnType("int");

                    b.Property<int?>("MaTuyen")
                        .HasColumnType("int");

                    b.Property<string>("TenChuyenXe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ThoiDiemDenDuKien")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ThoiDiemKhoiHanh")
                        .HasColumnType("datetime");

                    b.HasKey("MaChuyen")
                        .HasName("PK__ChuyenXe__0ED32A472A7B00B1");

                    b.HasIndex("BienSoXe");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaNhanVien1");

                    b.HasIndex("MaTaiXe");

                    b.HasIndex("MaTuyen");

                    b.ToTable("ChuyenXe", (string)null);
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.KhuyenMai", b =>
                {
                    b.Property<int>("MaKhuyenMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhuyenMai"), 1L, 1);

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<decimal>("PhanTramGiam")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("TenKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKhuyenMai")
                        .HasName("PK__KhuyenMa__6F56B3BD77E05726");

                    b.ToTable("KhuyenMai", (string)null);
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.LienHe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayGui")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("LienHe", (string)null);
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.Loaixe", b =>
                {
                    b.Property<int>("IdLoai")
                        .HasColumnType("int")
                        .HasColumnName("ID_LOAI");

                    b.Property<int>("Soghe")
                        .HasColumnType("int")
                        .HasColumnName("SOGHE");

                    b.Property<string>("Tenloai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENLOAI");

                    b.HasKey("IdLoai")
                        .HasName("PK__loaixe__994CB9EAC7B987C6");

                    b.ToTable("loaixe", (string)null);
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ChuThich")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaQuyen")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SDT");

                    b.HasKey("Id");

                    b.HasIndex("MaQuyen");

                    b.HasIndex(new[] { "Email" }, "UQ__NguoiDun__A9D10534EAA83623")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"), 1L, 1);

                    b.Property<long?>("Cccd")
                        .HasColumnType("bigint");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValueSql("(N'Nhân Viên')");

                    b.HasKey("MaNhanVien")
                        .HasName("PK__NhanVien__77B2CA47CD53549F");

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.PhanQuyen", b =>
                {
                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuyen"), 1L, 1);

                    b.Property<string>("TenQuyen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaQuyen")
                        .HasName("PK__PhanQuye__1D4B7ED45F686F58");

                    b.ToTable("PhanQuyen", (string)null);
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.PhieuDatVe", b =>
                {
                    b.Property<int>("MaPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieu"), 1L, 1);

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaKhuyenMai")
                        .HasColumnType("int");

                    b.Property<string>("MoMoTransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VnpTransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhieu")
                        .HasName("PK__PhieuDat__2660BFE00BC5E6E3");

                    b.HasIndex("MaKhuyenMai");

                    b.ToTable("PhieuDatVe", (string)null);
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"), 1L, 1);

                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaPhieu")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaThanhToan")
                        .HasName("PK__ThanhToa__D4B25844477DF218");

                    b.HasIndex("MaPhieu");

                    b.ToTable("ThanhToan", (string)null);
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.TuyenXe", b =>
                {
                    b.Property<int>("MaTuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTuyen"), 1L, 1);

                    b.Property<string>("DiemDen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DiemDi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("GiaHienHanh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaBenXeDen")
                        .HasColumnType("int");

                    b.Property<int>("MaBenXeDi")
                        .HasColumnType("int");

                    b.Property<int?>("QuangDuong")
                        .HasColumnType("int");

                    b.Property<int?>("SoNgayChayTrongTuan")
                        .HasColumnType("int");

                    b.HasKey("MaTuyen")
                        .HasName("PK__TuyenXe__B45760204FE10EA9");

                    b.HasIndex("MaBenXeDen");

                    b.HasIndex("MaBenXeDi");

                    b.ToTable("TuyenXe", (string)null);
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.VeXe", b =>
                {
                    b.Property<int>("MaVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVe"), 1L, 1);

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("IdVitri")
                        .HasColumnType("int");

                    b.Property<int?>("MaChuyen")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhieu")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Sđt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SĐT");

                    b.Property<string>("TenKh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenKH");

                    b.Property<string>("TenVe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVe")
                        .HasName("PK__VeXe__2725100FC96E40BB");

                    b.HasIndex("IdVitri");

                    b.HasIndex("MaChuyen");

                    b.HasIndex("MaPhieu");

                    b.ToTable("VeXe", (string)null);
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.Vitrighe", b =>
                {
                    b.Property<int>("IdVitri")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVitri"), 1L, 1);

                    b.Property<string>("Bienso")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Tenvitri")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("Trangthai")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.HasKey("IdVitri")
                        .HasName("PK__Vitrighe__5965B3AB6EFE223C");

                    b.HasIndex("Bienso");

                    b.ToTable("Vitrighe", (string)null);
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.Xe", b =>
                {
                    b.Property<string>("Bienso")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("BIENSO");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdLoai")
                        .HasColumnType("int")
                        .HasColumnName("ID_LOAI");

                    b.Property<string>("Tenxe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENXE");

                    b.HasKey("Bienso")
                        .HasName("PK__xe__2B719FCC31E3F52F");

                    b.HasIndex("IdLoai");

                    b.ToTable("xe", (string)null);
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.ChuyenXe", b =>
                {
                    b.HasOne("Asp.netWebDatVe.Models.Xe", "BienSoXeNavigation")
                        .WithMany("ChuyenXes")
                        .HasForeignKey("BienSoXe")
                        .HasConstraintName("FK_ChuyenXe_BienSoXe");

                    b.HasOne("Asp.netWebDatVe.Models.NhanVien", "MaNhanVienNavigation")
                        .WithMany("ChuyenXeMaNhanVienNavigations")
                        .HasForeignKey("MaNhanVien")
                        .HasConstraintName("FK_ChuyenXe_NhanVien_NhanVien");

                    b.HasOne("Asp.netWebDatVe.Models.NhanVien", "MaNhanVien1Navigation")
                        .WithMany("ChuyenXeMaNhanVien1Navigations")
                        .HasForeignKey("MaNhanVien1")
                        .HasConstraintName("FK_ChuyenXe_NhanVien_NhanVien1");

                    b.HasOne("Asp.netWebDatVe.Models.NhanVien", "MaTaiXeNavigation")
                        .WithMany("ChuyenXeMaTaiXeNavigations")
                        .HasForeignKey("MaTaiXe")
                        .HasConstraintName("FK_ChuyenXe_NhanVien_TaiXe");

                    b.HasOne("Asp.netWebDatVe.Models.TuyenXe", "MaTuyenNavigation")
                        .WithMany("ChuyenXes")
                        .HasForeignKey("MaTuyen")
                        .HasConstraintName("FK__ChuyenXe__MaTuye__3C69FB99");

                    b.Navigation("BienSoXeNavigation");

                    b.Navigation("MaNhanVien1Navigation");

                    b.Navigation("MaNhanVienNavigation");

                    b.Navigation("MaTaiXeNavigation");

                    b.Navigation("MaTuyenNavigation");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.NguoiDung", b =>
                {
                    b.HasOne("Asp.netWebDatVe.Models.PhanQuyen", "MaQuyenNavigation")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaQuyen")
                        .HasConstraintName("FK__NguoiDung__MaQuy__656C112C");

                    b.Navigation("MaQuyenNavigation");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.PhieuDatVe", b =>
                {
                    b.HasOne("Asp.netWebDatVe.Models.KhuyenMai", "MaKhuyenMaiNavigation")
                        .WithMany("PhieuDatVes")
                        .HasForeignKey("MaKhuyenMai")
                        .HasConstraintName("FK_PhieuDatVe_KhuyenMai");

                    b.Navigation("MaKhuyenMaiNavigation");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.ThanhToan", b =>
                {
                    b.HasOne("Asp.netWebDatVe.Models.PhieuDatVe", "MaPhieuNavigation")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaPhieu")
                        .IsRequired()
                        .HasConstraintName("FK__ThanhToan__MaPhi__7D0E9093");

                    b.Navigation("MaPhieuNavigation");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.TuyenXe", b =>
                {
                    b.HasOne("Asp.netWebDatVe.Models.BenXe", "MaBenXeDenNavigation")
                        .WithMany("TuyenXeMaBenXeDenNavigations")
                        .HasForeignKey("MaBenXeDen")
                        .IsRequired()
                        .HasConstraintName("fk_MaBenXeDen");

                    b.HasOne("Asp.netWebDatVe.Models.BenXe", "MaBenXeDiNavigation")
                        .WithMany("TuyenXeMaBenXeDiNavigations")
                        .HasForeignKey("MaBenXeDi")
                        .IsRequired()
                        .HasConstraintName("fk_MaBenXeDi");

                    b.Navigation("MaBenXeDenNavigation");

                    b.Navigation("MaBenXeDiNavigation");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.VeXe", b =>
                {
                    b.HasOne("Asp.netWebDatVe.Models.Vitrighe", "IdVitriNavigation")
                        .WithMany("VeXes")
                        .HasForeignKey("IdVitri")
                        .HasConstraintName("FK_VeXe_Vitrighe");

                    b.HasOne("Asp.netWebDatVe.Models.ChuyenXe", "MaChuyenNavigation")
                        .WithMany("VeXes")
                        .HasForeignKey("MaChuyen")
                        .HasConstraintName("FK__VeXe__MaChuyen__60A75C0F");

                    b.HasOne("Asp.netWebDatVe.Models.PhieuDatVe", "MaPhieuNavigation")
                        .WithMany("VeXes")
                        .HasForeignKey("MaPhieu")
                        .HasConstraintName("FK__VeXe__MaPhieu__5FB337D6");

                    b.Navigation("IdVitriNavigation");

                    b.Navigation("MaChuyenNavigation");

                    b.Navigation("MaPhieuNavigation");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.Vitrighe", b =>
                {
                    b.HasOne("Asp.netWebDatVe.Models.Xe", "BiensoNavigation")
                        .WithMany("Vitrighes")
                        .HasForeignKey("Bienso")
                        .IsRequired()
                        .HasConstraintName("FK_Vitrighe_Xe");

                    b.Navigation("BiensoNavigation");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.Xe", b =>
                {
                    b.HasOne("Asp.netWebDatVe.Models.Loaixe", "IdLoaiNavigation")
                        .WithMany("Xes")
                        .HasForeignKey("IdLoai")
                        .IsRequired()
                        .HasConstraintName("FK__xe__ID_LOAI__4316F928");

                    b.Navigation("IdLoaiNavigation");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.BenXe", b =>
                {
                    b.Navigation("TuyenXeMaBenXeDenNavigations");

                    b.Navigation("TuyenXeMaBenXeDiNavigations");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.ChuyenXe", b =>
                {
                    b.Navigation("VeXes");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.KhuyenMai", b =>
                {
                    b.Navigation("PhieuDatVes");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.Loaixe", b =>
                {
                    b.Navigation("Xes");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.NhanVien", b =>
                {
                    b.Navigation("ChuyenXeMaNhanVien1Navigations");

                    b.Navigation("ChuyenXeMaNhanVienNavigations");

                    b.Navigation("ChuyenXeMaTaiXeNavigations");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.PhanQuyen", b =>
                {
                    b.Navigation("NguoiDungs");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.PhieuDatVe", b =>
                {
                    b.Navigation("ThanhToans");

                    b.Navigation("VeXes");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.TuyenXe", b =>
                {
                    b.Navigation("ChuyenXes");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.Vitrighe", b =>
                {
                    b.Navigation("VeXes");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.Xe", b =>
                {
                    b.Navigation("ChuyenXes");

                    b.Navigation("Vitrighes");
                });
#pragma warning restore 612, 618
        }
    }
}
