// <auto-generated />
using System;
using Asp.netWebDatVe.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Asp.netWebDatVe.Migrations
{
    [DbContext(typeof(QLDatVeContext))]
    partial class QLDatVeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Asp.netWebDatVe.Models.BenXe", b =>
                {
                    b.Property<int>("MaBenXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBenXe"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenBenXe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaBenXe")
                        .HasName("PK__BenXe__436ED7BADC83220E");

                    b.ToTable("BenXe", (string)null);
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.BenXeDen", b =>
                {
                    b.Property<int>("MaBenXeDen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBenXeDen"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenBenXeDen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaBenXeDen")
                        .HasName("PK__BenXeDen__FA9521107644CDCA");

                    b.ToTable("BenXeDen", (string)null);
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.ChuyenXe", b =>
                {
                    b.Property<int>("MaChuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuyen"), 1L, 1);

                    b.Property<string>("BienSoXe")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal?>("GiaVe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MaTuyen")
                        .HasColumnType("int");

                    b.Property<string>("TenChuyenXe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ThoiDiemDenDuKien")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ThoiDiemKhoiHanh")
                        .HasColumnType("datetime");

                    b.HasKey("MaChuyen")
                        .HasName("PK__ChuyenXe__0ED32A472A7B00B1");

                    b.HasIndex("BienSoXe");

                    b.HasIndex("MaTuyen");

                    b.ToTable("ChuyenXe", (string)null);
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.Loaixe", b =>
                {
                    b.Property<int>("IdLoai")
                        .HasColumnType("int")
                        .HasColumnName("ID_LOAI");

                    b.Property<int>("Soghe")
                        .HasColumnType("int")
                        .HasColumnName("SOGHE");

                    b.Property<string>("Tenloai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENLOAI");

                    b.HasKey("IdLoai")
                        .HasName("PK__loaixe__994CB9EAC7B987C6");

                    b.ToTable("loaixe", (string)null);
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaQuyen")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SDT");

                    b.HasKey("Id");

                    b.HasIndex("MaQuyen");

                    b.HasIndex(new[] { "Email" }, "UQ__NguoiDun__A9D10534EAA83623")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.PhanQuyen", b =>
                {
                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuyen"), 1L, 1);

                    b.Property<string>("TenQuyen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaQuyen")
                        .HasName("PK__PhanQuye__1D4B7ED45F686F58");

                    b.ToTable("PhanQuyen", (string)null);
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.PhieuDatVe", b =>
                {
                    b.Property<int>("MaPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieu"), 1L, 1);

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaPhieu")
                        .HasName("PK__PhieuDat__2660BFE00BC5E6E3");

                    b.ToTable("PhieuDatVe", (string)null);
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.TuyenXe", b =>
                {
                    b.Property<int>("MaTuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTuyen"), 1L, 1);

                    b.Property<string>("DiemDen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DiemDi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("GiaHienHanh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MaBenXe")
                        .HasColumnType("int");

                    b.Property<int?>("MaBenXeDen")
                        .HasColumnType("int");

                    b.Property<int?>("QuangDuong")
                        .HasColumnType("int");

                    b.Property<int?>("SoNgayChayTrongTuan")
                        .HasColumnType("int");

                    b.HasKey("MaTuyen")
                        .HasName("PK__TuyenXe__B45760204FE10EA9");

                    b.HasIndex("MaBenXe");

                    b.HasIndex("MaBenXeDen");

                    b.ToTable("TuyenXe", (string)null);
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.VeXe", b =>
                {
                    b.Property<int>("MaVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVe"), 1L, 1);

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("IdVitri")
                        .HasColumnType("int")
                        .HasColumnName("ID_VITRI");

                    b.Property<int?>("MaChuyen")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhieu")
                        .HasColumnType("int");

                    b.Property<string>("TenKh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenKH");

                    b.Property<string>("TenVe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVe")
                        .HasName("PK__VeXe__2725100FC96E40BB");

                    b.HasIndex("IdVitri");

                    b.HasIndex("MaChuyen");

                    b.HasIndex("MaPhieu");

                    b.ToTable("VeXe", (string)null);
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.Vitrighe", b =>
                {
                    b.Property<int>("IdVitri")
                        .HasColumnType("int")
                        .HasColumnName("ID_VITRI");

                    b.Property<string>("Bienso")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("BIENSO");

                    b.Property<string>("Tenvitri")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENVITRI");

                    b.Property<bool?>("Trangthai")
                        .HasColumnType("bit")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("IdVitri")
                        .HasName("PK__vitrighe__121D67D0DAE6F32D");

                    b.HasIndex("Bienso");

                    b.ToTable("vitrighe", (string)null);
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.Xe", b =>
                {
                    b.Property<string>("Bienso")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("BIENSO");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdLoai")
                        .HasColumnType("int")
                        .HasColumnName("ID_LOAI");

                    b.Property<string>("Tenxe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENXE");

                    b.HasKey("Bienso")
                        .HasName("PK__xe__2B719FCC31E3F52F");

                    b.HasIndex("IdLoai");

                    b.ToTable("xe", (string)null);
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.ChuyenXe", b =>
                {
                    b.HasOne("Asp.netWebDatVe.Models.Xe", "BienSoXeNavigation")
                        .WithMany("ChuyenXes")
                        .HasForeignKey("BienSoXe")
                        .HasConstraintName("FK_ChuyenXe_BienSoXe");

                    b.HasOne("Asp.netWebDatVe.Models.TuyenXe", "MaTuyenNavigation")
                        .WithMany("ChuyenXes")
                        .HasForeignKey("MaTuyen")
                        .HasConstraintName("FK__ChuyenXe__MaTuye__3C69FB99");

                    b.Navigation("BienSoXeNavigation");

                    b.Navigation("MaTuyenNavigation");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.NguoiDung", b =>
                {
                    b.HasOne("Asp.netWebDatVe.Models.PhanQuyen", "MaQuyenNavigation")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaQuyen")
                        .HasConstraintName("FK__NguoiDung__MaQuy__656C112C");

                    b.Navigation("MaQuyenNavigation");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.TuyenXe", b =>
                {
                    b.HasOne("Asp.netWebDatVe.Models.BenXe", "MaBenXeNavigation")
                        .WithMany("TuyenXes")
                        .HasForeignKey("MaBenXe")
                        .HasConstraintName("FK_TuyenXe_BenXe");

                    b.HasOne("Asp.netWebDatVe.Models.BenXeDen", "MaBenXeDenNavigation")
                        .WithMany("TuyenXes")
                        .HasForeignKey("MaBenXeDen")
                        .HasConstraintName("FK_TuyenXe_BenXeDen");

                    b.Navigation("MaBenXeDenNavigation");

                    b.Navigation("MaBenXeNavigation");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.VeXe", b =>
                {
                    b.HasOne("Asp.netWebDatVe.Models.Vitrighe", "IdVitriNavigation")
                        .WithMany("VeXes")
                        .HasForeignKey("IdVitri")
                        .HasConstraintName("FK_VeXe_Vitrighe");

                    b.HasOne("Asp.netWebDatVe.Models.ChuyenXe", "MaChuyenNavigation")
                        .WithMany("VeXes")
                        .HasForeignKey("MaChuyen")
                        .HasConstraintName("FK__VeXe__MaChuyen__60A75C0F");

                    b.HasOne("Asp.netWebDatVe.Models.PhieuDatVe", "MaPhieuNavigation")
                        .WithMany("VeXes")
                        .HasForeignKey("MaPhieu")
                        .HasConstraintName("FK__VeXe__MaPhieu__5FB337D6");

                    b.Navigation("IdVitriNavigation");

                    b.Navigation("MaChuyenNavigation");

                    b.Navigation("MaPhieuNavigation");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.Vitrighe", b =>
                {
                    b.HasOne("Asp.netWebDatVe.Models.Xe", "BiensoNavigation")
                        .WithMany("Vitrighes")
                        .HasForeignKey("Bienso")
                        .IsRequired()
                        .HasConstraintName("FK__vitrighe__BIENSO__45F365D3");

                    b.Navigation("BiensoNavigation");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.Xe", b =>
                {
                    b.HasOne("Asp.netWebDatVe.Models.Loaixe", "IdLoaiNavigation")
                        .WithMany("Xes")
                        .HasForeignKey("IdLoai")
                        .IsRequired()
                        .HasConstraintName("FK__xe__ID_LOAI__4316F928");

                    b.Navigation("IdLoaiNavigation");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.BenXe", b =>
                {
                    b.Navigation("TuyenXes");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.BenXeDen", b =>
                {
                    b.Navigation("TuyenXes");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.ChuyenXe", b =>
                {
                    b.Navigation("VeXes");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.Loaixe", b =>
                {
                    b.Navigation("Xes");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.PhanQuyen", b =>
                {
                    b.Navigation("NguoiDungs");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.PhieuDatVe", b =>
                {
                    b.Navigation("VeXes");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.TuyenXe", b =>
                {
                    b.Navigation("ChuyenXes");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.Vitrighe", b =>
                {
                    b.Navigation("VeXes");
                });

            modelBuilder.Entity("Asp.netWebDatVe.Models.Xe", b =>
                {
                    b.Navigation("ChuyenXes");

                    b.Navigation("Vitrighes");
                });
#pragma warning restore 612, 618
        }
    }
}
